version: '3.8'

services:
  db:
    image: postgres:13 # Usa la imagen oficial de PostgreSQL
    container_name: esb_postgres_db
    environment:
      POSTGRES_DB: esb_catalogo_db # Nombre de la base de datos a crear
      POSTGRES_USER: esb_user      # Usuario de la base de datos (cambiar en producci칩n)
      POSTGRES_PASSWORD: esb_password # Contrase침a del usuario (cambiar en producci칩n)
    ports:
      - "5432:5432" # Mapea el puerto 5432 de tu m치quina al puerto 5432 del contenedor
    volumes:
      - db_data:/var/lib/postgresql/data # Persiste los datos de la base de datos
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Ejecuta scripts SQL al iniciar el contenedor
    restart: always # Asegura que el contenedor se reinicie si falla

volumes:
  db_data: